baseURL = ""
languageCode = "en-us"
title = "Aaron Brighton - Founder, Architect, Engineer"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-134712455-1"

[params]
    theme_color = "#333333"
    description = "Aaron Brighton - Founder, Architect, Engineer, passionate about information security, sustainable energy adoption and education that succeeds in engaging students."
    description_photo = "aaron-brighton.jpg"
    favicon = "favicon.ico"
    logo = "aaron-brighton.jpg"
    email = "aaron@aaronbrighton.ca"
#    facebook = ""
    twitter = "aaronbrighton"
#    dribbble = ""
    linkedin = "https://www.linkedin.com/in/aaronbrighton/"
#    medium = ""
#    github = ""
#    googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "aaron-brighton.jpg"
    subtitle = "Aaron Brighton"
    subsubtitle = "Founder, Architect, Engineer"

[params.projects]
    enable = true
    title = "Projects"
    subtitle = "I'm currently working on"

[params.publications]
    enable = true
    title = "Publications"
    subtitle = "I've written or contributed too"

[params.footer]
    enable = true
